### ISSUE TITLE
Error with bot

### ISSUE THREAD

**Issue by 3raden** [ericf1/ftwbot#11]
Traceback (most recent call last):
  File "/home/ubuntu/ftwbot/src/bot.py", line 513, in <module>
    main_loop.start()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/ext/tasks/__init__.py", line 398, in start
    self._task = asyncio.create_task(self._loop(*args, **kwargs))
  File "/usr/lib/python3.10/asyncio/tasks.py", line 336, in create_task
    loop = events.get_running_loop()
RuntimeError: no running event loop
sys:1: RuntimeWarning: coroutine 'Loop._loop' was never awaited

**Comment by ericf1** [comment]
Hi! We are currently still working on developing the bot. We should have a demo version out very soon!
